### ISSUE TITLE
Add missing bridges

### ISSUE THREAD

**Issue by ademcan** [cyber-republic/react-native-elastos-carrier#17]

**Comment by liyangwood** [comment]
https://github.com/cyber-republic/react-native-elastos-carrier/blob/dev/doc/todo.md
here is the missing api list

start to complete these bridges.

**Comment by ademcan** [comment]
That's great Jacky 👍

**Comment by liyangwood** [comment]
complete missing api for iOS

**Comment by liyangwood** [comment]
start to deal with the Android part.

**Comment by liyangwood** [comment]
@ademcan please merge this PR https://github.com/cyber-republic/react-native-elastos-carrier/pull/28
complete the missing api for both iOS and Android

**Comment by liyangwood** [comment]
HI, Adem, looks like could close this issue and let me continue others.

**Comment by ademcan** [comment]
Sure, thanks Jacky and well done!
